import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import vm from 'node:vm';import {spawnSync} from 'node:child_process';
const python=process.env.PYTHON||(process.platform==='win32'?'python':'python3');
test('Each interactive HTML entrypoint loads its owned code as a module',()=>{for(const [f,js]of [['admin','app'],['member','member'],['verify','verify'],['deployment','deployment']])assert.match(fs.readFileSync(`frontend/${f}.html`,'utf8'),new RegExp('<script[^>]*type="module"[^>]*src="'+js+'.js"'));});
test('Browser verifier source byte-identical to canonical source',()=>{for(const f of ['ticket-request.mjs','ethers-adapter.mjs'])assert.equal(fs.readFileSync('shared/'+f,'utf8'),fs.readFileSync('frontend/shared/'+f,'utf8'));});
test('Member, operator and CLI use the same canonical protocol and production adapter',()=>{for(const f of ['frontend/member.js','frontend/verify.js','tools/verify_ticket_request.mjs']){const src=fs.readFileSync(f,'utf8');assert.match(src,/import[^\n]*verifyTicketRequest[^\n]*ticket-request\.mjs/);assert.match(src,/import[^\n]*createEthersIO[^\n]*ethers-adapter\.mjs/);}});
test('Configurator writes only trusted public settings, no request endpoint',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'agi-config-'));try{const out=path.join(dir,'config.js');const r=spawnSync(python,['scripts/configure.py','--contract','0x'+'11'.repeat(20),'--runtime-code-hash','0x'+'22'.repeat(32),'--origin','https://claims.example.org','--entitlement','IA101_2026_09_22','--output',out],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);const ctx={window:{}};vm.runInNewContext(fs.readFileSync(out,'utf8'),ctx);const c=ctx.window.AGI_CONFIG;assert.equal(c.registryCodeHash,'0x'+'22'.repeat(32));assert.equal(c.chainId,1);assert.equal(c.expectedOrigin,'https://claims.example.org');assert(!Object.hasOwn(c,'requestEndpoint'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('Configurator rejects incomplete, insecure or backend-enabled configuration',()=>{const args=['scripts/configure.py','--contract','0x'+'11'.repeat(20),'--entitlement','IA101_2026_09_22'];for(const more of [['--origin','https://claims.example.org'],['--runtime-code-hash','0x'+'22'.repeat(32),'--origin','http://claims.example.org'],['--runtime-code-hash','0x'+'22'.repeat(32),'--origin','https://claims.example.org/path'],['--runtime-code-hash','0x'+'22'.repeat(32),'--origin','https://claims.example.org','--request-endpoint','https://relay.example.org/request']])assert.notEqual(spawnSync(python,[...args,...more],{encoding:'utf8'}).status,0);});

test('Public build copies only named shared/vendor assets, never whole directories',()=>{const s=fs.readFileSync('scripts/package.mjs','utf8');assert(!s.includes('cpSync'));assert(s.includes("['ticket-request.mjs','ethers-adapter.mjs','deployment-policy.mjs']"));assert(s.includes("['ethers.umd.min.js','ETHERS_LICENSE.md']"));});
