import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {fixture,NOW} from './fixtures.mjs';
import {id,namehash,signMessage,verifyMessage,walletAddress} from './crypto-reference.mjs';
import {validatePacket,verifyTicketRequest,requestMessage,claimKey,recipientCommitment,SCHEMA,preparePacket} from '../shared/ticket-request.mjs';
const opts={now:NOW},rejects=(fn,code)=>assert.rejects(fn,e=>e.code===code,code);
test('Known Ethereum vectors, TEST-ONLY reference not production ethers',()=>{
 assert.equal(id(''),'0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470');
 assert.equal(namehash('club.agi.eth'),'0x39eb848f88bdfb0a6371096249dd451f56859dfe2cd3ddeab1e26d5bb68ede16');
 assert.equal(walletAddress(1n),'0x7e5f4552091a69125d5dfcb7b8c2659029395bdf');
 assert.equal(verifyMessage('AGI Club',signMessage('AGI Club')),walletAddress(1n));
});
test('Valid v3 receipt binds recipient; not a ticket or mailbox verification',async()=>{const f=await fixture(),r=await verifyTicketRequest(f.packet,f.policy,f.io,opts);assert.equal(r.status,'VERIFIED_REQUEST_NOT_A_TICKET');assert.equal(r.recipient.email,'alice@example.org');assert.equal(r.ticketIssued,false);assert.equal(r.mailboxControlVerified,false);assert(!('email'in r.payload));});
test('WebCrypto commitment independently matches node crypto SHA-256',async()=>{const f=await fixture(),r=f.packet.recipient;assert.equal(await recipientCommitment(r),'0x'+createHash('sha256').update(JSON.stringify([SCHEMA+'/recipient',r.salt,r.name,r.email])).digest('hex'));});
test('Wallet message excludes recipient text AND the private salt',async()=>{const f=await fixture();for(const value of Object.values(f.packet.recipient))assert(!f.packet.message.includes(value));});
test('RPC IO sees no plaintext recipient or private salt',async()=>{const f=await fixture();await verifyTicketRequest(f.packet,f.policy,f.io,opts);const log=JSON.stringify(f.calls);for(const value of Object.values(f.packet.recipient)){assert(!log.includes(value));assert(!log.includes(Buffer.from(value).toString('hex')));}for(const c of f.calls.filter(x=>x.method==='claim'))assert.deepEqual(Object.keys(c.q).sort(),['entitlementId','membershipNode']);});
test('Same recipient gets distinct commitments with independent salts',async()=>{const a=await fixture(),b=await fixture();assert.notEqual(a.packet.recipient.salt,b.packet.recipient.salt);assert.notEqual(a.packet.payload.recipientCommitment,b.packet.payload.recipientCommitment);});
for(const [field,value,code]of [
 ['schema','AGIClubTicketRequest/2.2','UNSUPPORTED_SCHEMA'],['origin','https://evil.example','WRONG_SCOPE'],['chainId',11155111,'WRONG_SCOPE'],['registry','0x'+'33'.repeat(20),'WRONG_SCOPE'],['entitlementId',id('OTHER'),'ENTITLEMENT_NOT_ENABLED'],['membershipLabel','x.alice','INVALID_MEMBERSHIP'],['membershipNode','0x'+'00'.repeat(32),'INVALID_MEMBERSHIP'],['claimRevision',0,'INVALID_CLAIM'],['claimRevision',4294967296,'INVALID_CLAIM'],['claimant','0x'+'00'.repeat(20),'INVALID_CLAIM'],['issuedAt',NOW+301,'INVALID_TIME'],['issuedAt',-1,'INVALID_TIME'],['expiresAt',NOW,'REQUEST_EXPIRED'],['expiresAt',NOW+8*86400,'INVALID_TIME'],['nonce','0x12','INVALID_NONCE'],['recipientCommitment','bad','INVALID_COMMITMENT']
])test('Reject invalid '+field+' / '+code,async()=>{const f=await fixture();f.packet.payload[field]=value;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),code);});
for(const [field,value,code]of [['name','A\nB','INVALID_CONTACT'],['email','a@example.org\r\nBcc:x@evil.org','INVALID_CONTACT'],['email','invalid','INVALID_CONTACT'],['name','\u202eHidden','INVALID_CONTACT'],['salt','0x12','INVALID_SALT'],['salt','0x'+'00'.repeat(32),'INVALID_SALT']])test('Reject unsafe private '+field+' '+code,async()=>{const f=await fixture();f.packet.recipient[field]=value;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),code);});
for(const [field,value]of [['name','Mallory'],['email','mallory@example.org'],['salt','0x'+'cd'.repeat(32)]]){
 test('Changed private '+field+' rejected without contacting chain',async()=>{const f=await fixture();f.packet.recipient[field]=value;let calls=0;f.io.chainId=async()=>{calls++;return 1n;};await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'RECIPIENT_COMMITMENT_MISMATCH');assert.equal(calls,0);});
 test('Recomputed commitment cannot reuse signature after changing '+field,async()=>{const f=await fixture();f.packet.recipient[field]=value;f.packet.payload.recipientCommitment=await recipientCommitment(f.packet.recipient);f.packet.message=requestMessage(f.packet.payload);await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'INVALID_SIGNATURE');});
}
for(const [field,value]of [['nonce','0x'+'cd'.repeat(16)],['claimRevision',2],['issuedAt',NOW-20],['expiresAt',NOW+3000]])test('Unsigned scoped '+field+' alteration rejected',async()=>{const f=await fixture();f.packet.payload[field]=value;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'MESSAGE_PAYLOAD_MISMATCH');});
test('Extra top-level email field rejected',async()=>{const f=await fixture();f.packet.email='mallory@example.org';await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'INVALID_SCHEMA');});
test('Extra payload and private recipient fields rejected',async()=>{const f=await fixture();f.packet.payload.allowExpired=true;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'INVALID_SCHEMA');delete f.packet.payload.allowExpired;f.packet.recipient.debug=true;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'INVALID_RECIPIENT_SCHEMA');});
test('Legacy flat and v2 packet structures fail closed',async()=>{const f=await fixture();await rejects(()=>verifyTicketRequest({...f.packet.payload,message:f.packet.message,signature:f.packet.signature},f.policy,f.io,opts),'INVALID_SCHEMA');delete f.packet.recipient;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'INVALID_SCHEMA');});
test('Canonical key order is independent of JSON insertion order',async()=>{const f=await fixture();f.packet.payload=Object.fromEntries(Object.entries(f.packet.payload).reverse());await verifyTicketRequest(f.packet,f.policy,f.io,opts);});
test('Wrong signing key rejected',async()=>{const f=await fixture();f.packet.signature=signMessage(f.packet.message,2n);await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'INVALID_SIGNATURE');});
test('Bad signature format rejected',async()=>{const f=await fixture();f.packet.signature='0xZZ';await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'INVALID_SIGNATURE_FORMAT');});
test('Wrong provider chain rejected',async()=>{const f=await fixture();f.state.chain=31337n;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'WRONG_CHAIN');});
for(const [key,value]of [['version','2.1.0'],['ens','0x'+'77'.repeat(20)],['wrapper','0x'+'88'.repeat(20)],['root',id('fake')],['codeHash',id('fake-bytecode')]])test('Wrong deployed identity '+key+' rejected',async()=>{const f=await fixture();f.state.identity[key]=value;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'WRONG_REGISTRY');});
for(const [key,value]of [['status',2],['revision',2],['claimant',walletAddress(2n)]])test('Changed current claim '+key+' blocks issuance',async()=>{const f=await fixture();f.state.claimL[key]=value;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'CLAIM_NOT_CURRENT');});
test('Pending finality is not invalid recipient identity',async()=>{const f=await fixture();f.state.claimF.status=0;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'WAITING_FOR_FINALITY');});
test('Contract-wallet policy changed in latest state rejected',async()=>{const f=await fixture();f.state.signaturePolicy=(_,__,___,b)=>b===100;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'INVALID_SIGNATURE');});
test('Reorganization detected on read-back',async()=>{const f=await fixture();f.io.block=async t=>t==='finalized'?f.state.finalized:t==='latest'?f.state.latest:{number:t,hash:id('reorg')};await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'CHAIN_CHANGED_RETRY');});
test('No server acceptance or expiry-bypass option in static-only protocol',async()=>{const f=await fixture();await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,{now:NOW+4000,acceptedAt:NOW}),'REQUEST_EXPIRED');});
test('Missing runtime hash cannot disable verifier',async()=>{const f=await fixture();delete f.policy.registryCodeHash;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'POLICY_NOT_CONFIGURED');});
for(const origin of ['http://claims.example.org','https://claims.example.org/path','https://u:p@claims.example.org','https://claims.example.org/'])test('Noncanonical policy origin rejected: '+origin,async()=>{const f=await fixture();f.policy.origin=origin;await rejects(()=>verifyTicketRequest(f.packet,f.policy,f.io,opts),'POLICY_NOT_CONFIGURED');});
test('Claim key cannot be reset by a new signature, recipient or revision',async()=>{const a=await fixture(),b=await fixture();b.packet.payload.claimRevision=2;assert.equal(claimKey(a.packet.payload),claimKey(b.packet.payload));});
test('Safe error codes do not echo supplied private fields',async()=>{const f=await fixture();f.packet.recipient.email='secret\n@invalid';try{await validatePacket(f.packet,f.policy,f.io.crypto,opts);assert.fail('Expected rejection');}catch(e){assert.equal(e.message,'INVALID_CONTACT');assert(!e.message.includes('secret'));}});
