'use strict';
(() => {
const $=id=>document.getElementById(id), CFG=window.AGI_CONFIG||{}, PAGE=document.body.dataset.page;
const ENS='0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e', WRAPPER='0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401';
const ABI=[
'function VERSION() view returns(string)','function CANONICAL_ENS() view returns(address)','function CANONICAL_WRAPPER() view returns(address)',
'function ensRegistry() view returns(address)','function adminNameWrapper() view returns(address)','function admin() view returns(address)','function paused() view returns(bool)',
'function CLUB_AGI_ETH_NODE() view returns(bytes32)','function entitlementCount() view returns(uint256)','function entitlementIdsPage(uint256,uint256) view returns(bytes32[])',
'function entitlement(bytes32) view returns(bytes32,bytes32,uint64,uint64,uint64,uint64,uint64,uint8,bool)',
'function titleFR(bytes32) view returns(string)','function titleEN(bytes32) view returns(string)','function metadataURI(bytes32) view returns(string)',
'function claimRecord(bytes32,bytes32) view returns(address,uint64,uint64,uint64,uint32,uint8)',
'function claimNodesPage(bytes32,uint256,uint256) view returns(bytes32[])','function claimNodeCount(bytes32) view returns(uint256)',
'function claimability(bytes32,address,string) view returns(uint8,bytes32,address,address,uint8,bool,bool,uint64,uint64,uint64,uint8)',
'function createEntitlement(bytes32,bytes32,uint64,uint64,uint64,uint8,bytes32)',
'function duplicateEntitlement(bytes32,bytes32)','function setEntitlementState(bytes32,uint8)','function setCapacity(bytes32,uint64)','function setWindow(bytes32,uint64,uint64)',
'function setCategory(bytes32,bytes32)','function setDescriptor(bytes32,string,string,string,bytes32)',
'function adminGrantBatchToCurrentOwners(bytes32,string[])','function adminGrantClaimOverride(bytes32,string,address,bytes32)',
'function revokeBatch(bytes32,string[],bytes32)','function reinstateClaim(bytes32,string)','function reassignRevokedClaim(bytes32,string,address)',
'function setSupportedNameWrapper(address,bool)','function pause()','function unpause()','function claim(bytes32,string)',
'error AdminUnavailable()','error NotClubAdmin(address,address)','error ClaimRejected(uint8)','error CapacityFull(bytes32)','error CapacityBelowActiveClaims(uint64,uint64)',
'error EntitlementAlreadyExists(bytes32)','error InvalidDescriptor()','error InvalidBatchSize()','error InvalidTimeWindow(uint64,uint64)','error EnforcedPause()'
];
let provider, signer, contract, account='', root='', demo=false, selected='', entries=[], auditRows=[], signedPacket=null, txPlan=null, offset=0, connected=false, currentMember=null, requestEpoch=0, txInFlight=false;
const logEntries=[];const states=['Inconnu','Brouillon','Ouvert','Fermé','Archivé'];
const claimStates=['Disponible','Registre en pause','Nom non admissible','Avantage inconnu','En brouillon','Fermé','Archivé','Pas encore ouvert','Période terminée','Déjà réclamé','Révoqué','Membership non trouvé','Le wallet n’est pas le détenteur','Membership expiré','Contingent complet'];
function status(s,bad=false){if($('status')){$('status').textContent=s;$('status').style.color=bad?'var(--red)':'var(--green)';}}
function log(s){logEntries.push({time:new Date().toISOString(),message:s});if($('log'))$('log').textContent=logEntries.slice(-30).map(x=>x.time+' · '+x.message).join('\n');}
function showError(e){let text=e?.shortMessage||e?.reason||e?.message||String(e);status(text,true);log('ERREUR : '+text);}
function bind(id,fn){const el=$(id);if(!el)return;el.addEventListener('click',async()=>{if(el.dataset.busy==='1')return;el.dataset.busy='1';el.setAttribute('aria-busy','true');try{await fn();}catch(e){showError(e);}finally{delete el.dataset.busy;el.removeAttribute('aria-busy');}});}
function download(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function needEthers(){if(!window.ethers)throw Error('Le portail n’a pas été construit correctement (ethers absent). Aucune transaction n’est possible. Contactez l’organisateur. La démonstration reste fictive.');}
function key(raw){raw=String(raw).trim();if(/^0x[0-9a-fA-F]{64}$/.test(raw))return raw;if(!/^[A-Z0-9][A-Z0-9_-]{0,127}$/.test(raw))throw Error('Identifiant : lettres majuscules, chiffres, tirets ou soulignés, 128 caractères maximum.');if(demo)return 'DEMO:'+raw;needEthers();return ethers.id(raw);}
function label(raw){let a=String(raw).trim().toLowerCase().replace(/\.club\.agi\.eth$/,'');if(!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(a))throw Error('Saisissez un unique label ASCII AGI Club. Les noms Unicode ne sont pas pris en charge dans cette version.');return a;}
function integer(id){const x=$(id).value.trim();if(!/^\d+$/.test(x)||BigInt(x)>1000000n)throw Error('Quota : entier entre 0 et 1 000 000.');return BigInt(x);}
function time(id){let t=$(id).value.trim();if(!t)return 0n;if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d(?::\d\d)?Z$/.test(t))throw Error('Date UTC requise, par exemple 2026-09-22T23:00:00Z.');let n=Date.parse(t);if(!Number.isFinite(n))throw Error('Date non valide.');return BigInt(Math.floor(n/1000));}
function dates(){let a=time('opens'),b=time('closes');if(a&&b&&b<=a)throw Error('La fermeture doit suivre l’ouverture.');return[a,b];}
function iso(n){return Number(n)?new Date(Number(n)*1000).toISOString().replace('.000',''):'';}
function vals(id){if(!$(id))return'';return $(id).value.trim();}
function idRequired(){if(!selected)throw Error('Sélectionnez un avantage du catalogue.');return selected;}
function members(){let x=vals('labels').split(/[\n,]/).map(x=>x.trim()).filter(Boolean).map(label);if(!x.length||x.length>50||new Set(x).size!==x.length)throw Error('De 1 à 50 memberships distincts sont requis.');return x;}
function oneMember(){let l=members();if(l.length!==1)throw Error('Cette correction exige exactement un membership.');return l[0];}
function hashReason(){if(!vals('reason'))throw Error('Indiquez une référence de correction sans renseignement personnel.');return demo?'DEMO:REASON':ethers.id(vals('reason'));}
function recipient(){needEthers();if(!ethers.isAddress(vals('recipient'))||vals('recipient')===ethers.ZeroAddress)throw Error('Wallet destinataire non valide.');return ethers.getAddress(vals('recipient'));}
async function assertLive(){needEthers();if(!CFG.expectedOrigin||!CFG.expectedOrigin.startsWith('https://')||location.origin!==CFG.expectedOrigin)throw Error('Origine officielle HTTPS absente ou différente. Aucune transaction autorisée par cette interface.');if(demo||!provider||!contract||!signer)throw Error('Connectez le wallet en mode réel.');if(Number(BigInt(await window.ethereum.request({method:'eth_chainId'})))!==1)throw Error('Ethereum mainnet requis.');const a=await window.ethereum.request({method:'eth_accounts'});if(!a?.[0]||a[0].toLowerCase()!==account.toLowerCase())throw Error('Le wallet a changé : reconnectez-vous.');}
async function connect(){needEthers();if(!ethers.isAddress(CFG.registryAddress||'')||CFG.registryAddress===ethers.ZeroAddress)throw Error('Le contrat n’est pas configuré. Aucun déploiement n’est fourni. Utilisez la démonstration ou renseignez config.js après déploiement.');if(!window.ethereum?.request)throw Error('Ouvrez la page dans un navigateur avec wallet Ethereum. Sur mobile, utilisez le navigateur de votre wallet.');await window.ethereum.request({method:'eth_requestAccounts'});if(BigInt(await window.ethereum.request({method:'eth_chainId'}))!==1n){await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1'}]});}provider=new ethers.BrowserProvider(window.ethereum);signer=await provider.getSigner();account=await signer.getAddress();contract=new ethers.Contract(CFG.registryAddress,ABI,signer);demo=false;await assertLive();const deployedCode=await provider.getCode(CFG.registryAddress);if(deployedCode==='0x')throw Error('Aucun contrat à cette adresse.');if(!/^0x[0-9a-f]{64}$/.test(CFG.registryCodeHash||'')||ethers.keccak256(deployedCode)!==CFG.registryCodeHash)throw Error('Empreinte du contrat absente ou différente du code approuvé. Ne signez pas.');const[ver,ens,wrap,ce,cw,rn]=await Promise.all([contract.VERSION(),contract.ensRegistry(),contract.adminNameWrapper(),contract.CANONICAL_ENS(),contract.CANONICAL_WRAPPER(),contract.CLUB_AGI_ETH_NODE()]);if(ver!=='2.1.1'||ens.toLowerCase()!==ENS.toLowerCase()||ce.toLowerCase()!==ENS.toLowerCase()||wrap.toLowerCase()!==WRAPPER.toLowerCase()||cw.toLowerCase()!==WRAPPER.toLowerCase()||rn!==ethers.namehash('club.agi.eth'))throw Error('Contrat ou sources d’autorité inattendus. Ne signez pas.');connected=true;offset=0;entries=[];signedPacket=null;currentMember=null;await refresh();log('Configuration de production et chaîne vérifiées. Cela ne constitue pas un audit du bytecode.');}
function renderAuthority(){if(!$('authority'))return;$('authority').textContent=demo?'DÉMONSTRATION — aucun droit réel':root&&root.toLowerCase()===account.toLowerCase()?'ADMIN · club.agi.eth':'LECTURE SEULE';$('authority').className='tag '+(demo?'warn':root&&root.toLowerCase()===account.toLowerCase()?'good':'');if($('connection'))$('connection').textContent=demo?'Simulation locale · aucun wallet · aucune transaction':`Wallet : ${account}\nAdmin actuel : ${root}\nContrat : ${CFG.registryAddress}`;}
function renderCatalog(){if(!$('catalog'))return;$('catalog').replaceChildren();for(const e of entries){const box=document.createElement('article');box.className='benefit';let d=document.createElement('div'),h=document.createElement('h3'),t=document.createElement('p'),code=document.createElement('code'),btn=document.createElement('button');h.textContent=e.fr||e.id; t.className='small muted';t.textContent=states[e.state]+' · '+e.active+' réclamations actives · '+(e.cap?e.cap+' places':'sans plafond');code.textContent=e.id;btn.textContent='Gérer';btn.onclick=()=>select(e);d.append(h,t,code);box.append(d,btn);$('catalog').append(box);}if($('count'))$('count').textContent=String(entries.length)+(entries.length<Number(window.totalCount||entries.length)?'+':'');}
function select(e){selected=e.id;$('selected').textContent='Identifiant : '+e.id;$('canonical').value=e.name||e.id;$('state').value=String(e.state);$('capacity').value=String(e.cap);$('opens').value=iso(e.opens);$('closes').value=iso(e.closes);$('titleFR').value=e.fr||'';$('titleEN').value=e.en||'';$('metadataURI').value=e.uri||'';$('metadataHash').value=e.hash==='0x'+'0'.repeat(64)?'':e.hash||'';$('stateStat').textContent=states[e.state];$('claimsStat').textContent=String(e.active);$('remainingStat').textContent=e.cap?String(Math.max(0,e.cap-e.active)):'∞';$('create').disabled=true;}
async function refresh(){if(demo){renderCatalog();renderAuthority();return;}if(!contract){status('Connectez le wallet ou ouvrez la démonstration.');return;}await assertLive();root=await contract.admin();renderAuthority();if(PAGE==='member'&&$('benefitSelect')){const ids=await contract.entitlementIdsPage(0,100);$('benefitSelect').replaceChildren();for(const id of ids){const en=await contract.entitlement(id);if(!en[8]||Number(en[7])===1||Number(en[7])===4)continue;const op=document.createElement('option');op.value=id;op.textContent=(await contract.titleFR(id))||id;$('benefitSelect').append(op);}if($('benefitSelect').options.length){$('canonical').value=$('benefitSelect').value;}else{$('canonical').value=CFG.defaultEntitlement||'IA101_2026_09_22';}}if(PAGE==='admin'){window.totalCount=Number(await contract.entitlementCount());const ids=await contract.entitlementIdsPage(0,Math.max(1,Math.min(offset+50,100)));entries=[];for(const id of ids){const[e,fr,en,uri]=await Promise.all([contract.entitlement(id),contract.titleFR(id),contract.titleEN(id),contract.metadataURI(id)]);entries.push({id,category:e[0],hash:e[1],cap:Number(e[2]),active:Number(e[3]),unique:Number(e[4]),opens:e[5],closes:e[6],state:Number(e[7]),fr,en,uri});}renderCatalog();const item=entries.find(e=>e.id===selected);if(item)select(item);status((await contract.paused())?'Les réclamations publiques sont en pause.':'Registre lu sur Ethereum.');}}
function startDemo(){requestEpoch++;demo=true;connected=false;contract=null;provider=null;signer=null;account='DEMO-ADMIN';root='DEMO-ADMIN';selected='';entries=[{id:'DEMO:IA101_2026_09_22',name:'IA101_2026_09_22',fr:'IA 101 — Admission membre offerte',en:'AI 101 — Complimentary member admission',state:1,cap:50,active:0,unique:0,opens:0,closes:0,hash:'',uri:''}];signedPacket=null;currentMember=null;renderAuthority();renderCatalog();if($('modeNotice'))$('modeNotice').textContent='DÉMONSTRATION LOCALE. Données fictives ; aucun droit réel, aucune preuve blockchain, aucun courriel envoyé. Actualiser la page remet la démonstration à zéro.';status('Explorez les commandes sans signature et sans frais.');if(PAGE==='admin')select(entries[0]);log('Mode démonstration activé.');}
async function preview(method,args,summary){if(demo){if(!confirm('DÉMONSTRATION uniquement\n'+summary+'\nSimuler cette action ?'))return;demoMutation(method,args);return;}await assertLive();root=await contract.admin();if(root===ethers.ZeroAddress)throw Error('Autorité indisponible : vérifiez la détention ENS et son échéance.');const data=contract.interface.encodeFunctionData(method,args);const isSelf=method==='claim';if(!isSelf&&root.toLowerCase()!==account.toLowerCase()){if((await provider.getCode(root))==='0x')throw Error('Lecture seule : le wallet connecté ne détient pas club.agi.eth.');txPlan={method,args,data,summary,safe:true,from:root};}else txPlan={method,args,data,summary,safe:false,from:account};$('confirmText').textContent=summary+(txPlan.safe?'\nL’admin est un contrat : exportez et exécutez la transaction depuis ce wallet, pas depuis votre EOA.':'');$('confirmData').textContent=JSON.stringify({chainId:1,contract:CFG.registryAddress,from:txPlan.from,method,args},(_,v)=>typeof v==='bigint'?v.toString():v,2);$('approveConfirm').disabled=txPlan.safe;$('exportConfirm').hidden=isSelf;$('confirm').showModal();}
async function approve(){if(txInFlight)throw Error('Une transaction est déjà en cours. Attendez sa confirmation.');txInFlight=true;try{const plan=txPlan;$('confirm').close();if(!plan)return;await assertLive();if(plan.method!=='claim'&&(await contract.admin()).toLowerCase()!==account.toLowerCase())throw Error('L’administrateur a changé. Transaction refusée.');status('Simulation de la transaction…');await contract[plan.method].staticCall(...plan.args);const gas=await contract[plan.method].estimateGas(...plan.args);status('Confirmez la transaction dans votre wallet.');const sent=await contract[plan.method](...plan.args,{gasLimit:gas*120n/100n});log('Transaction soumise : '+sent.hash);status('Transaction en attente. Ne soumettez pas de doublon.\n'+sent.hash);await sent.wait(2);log('Deux confirmations : '+sent.hash);status('Transaction confirmée.');if(PAGE==='admin')await refresh();}finally{txInFlight=false;}}
function demoMutation(method,a){let e=entries.find(e=>e.id===a[0]);if(method==='createEntitlement'){if(entries.some(x=>x.id===a[0]))throw Error('Identifiant déjà utilisé.');entries.push({id:a[0],name:a[0].slice(5),fr:a[0].slice(5),en:'',category:a[1],cap:Number(a[2]),active:0,unique:0,opens:a[3],closes:a[4],state:1,hash:'',uri:''});e=entries.at(-1);}
else if(method==='duplicateEntitlement'){if(!e)throw Error('Avantage absent.');if(entries.some(x=>x.id===a[1]))throw Error('Identifiant déjà utilisé.');entries.push({...e,id:a[1],name:a[1].slice(5),fr:'Copie à configurer',en:'',state:1,active:0,unique:0,opens:0,closes:0,hash:'',uri:''});e=entries.at(-1);}
else if(method==='setEntitlementState')e.state=Number(a[1]);else if(method==='setCapacity'){if(Number(a[1])&&Number(a[1])<e.active)throw Error('Quota inférieur aux réclamations actives.');e.cap=Number(a[1]);}else if(method==='setWindow'){e.opens=a[1];e.closes=a[2];}else if(method==='setCategory')e.category=a[1];else if(method==='setDescriptor'){[e.fr,e.en,e.uri,e.hash]=a.slice(1);}else if(method==='adminGrantBatchToCurrentOwners'){if(e.cap&&e.active+a[1].length>e.cap)throw Error('Contingent complet.');e.active+=a[1].length;e.unique+=a[1].length;}else if(method==='claim'){currentMember={label:label(vals('memberLabel')),id:a[0],claimed:true};$('eligibility').textContent='DÉMO : réclamation fictive enregistrée.';$('claim').disabled=true;$('request').disabled=false;}else{status('Action simulée : '+method+'. Consultez les tests EVM pour les garanties réelles.');}log('DÉMO : '+method);renderCatalog();if(e&&PAGE==='admin')select(e);}
async function audit(){if(demo){auditRows=[{simulation:true,note:'Relevé fictif uniquement',entitlement:selected,active:entries.find(x=>x.id===selected)?.active||0}];$('auditData').textContent=JSON.stringify(auditRows,null,2);return;}await assertLive();const id=idRequired();let n=Number(await contract.claimNodeCount(id));auditRows=[];for(let o=0;o<n;o+=100){for(const node of await contract.claimNodesPage(id,o,100)){const r=await contract.claimRecord(id,node);auditRows.push({entitlementId:id,membershipNode:node,claimant:r[0],status:Number(r[5])===1?'ACTIVE':'REVOKED',revision:Number(r[4]),firstClaimedAt:iso(r[1]),lastActivatedAt:iso(r[2]),revokedAt:iso(r[3])});}}$('auditData').textContent=JSON.stringify(auditRows,null,2);}
bind('connect',connect);bind('demo',startDemo);bind('refresh',refresh);bind('lang',()=>window.open('index.html','_blank','noopener'));if($('lang'))$('lang').textContent='Accueil';
bind('cancelConfirm',()=>$('confirm').close());bind('approveConfirm',approve);bind('exportConfirm',()=>{if(!txPlan)throw Error('Aucune transaction préparée.');download('AGI_CLUB_UNSIGNED_TRANSACTION.json',{chainId:1,to:CFG.registryAddress,value:'0',from:txPlan.from,data:txPlan.data,description:txPlan.summary});});
bind('showCreate',()=>{selected='';$('selected').textContent='Nouvel avantage · Identifiant immuable';$('canonical').value='';for(const f of ['titleFR','titleEN','metadataURI','metadataHash','opens','closes'])if($(f))$(f).value='';$('stateStat').textContent='Nouveau';$('claimsStat').textContent='0';$('remainingStat').textContent='—';$('create').disabled=false;});
bind('loadMore',async()=>{if(demo)return;if(!contract)throw Error('Connectez le wallet.');offset=entries.length;const ids=await contract.entitlementIdsPage(offset,50);for(const id of ids){const e=await contract.entitlement(id);entries.push({id,category:e[0],hash:e[1],cap:Number(e[2]),active:Number(e[3]),unique:Number(e[4]),opens:e[5],closes:e[6],state:Number(e[7]),fr:await contract.titleFR(id),en:await contract.titleEN(id),uri:await contract.metadataURI(id)});}renderCatalog();});
bind('create',()=>{const d=dates();return preview('createEntitlement',[key(vals('canonical')),key(vals('category')),integer('capacity'),...d,1,demo?'DEMO:ZERO':ethers.ZeroHash],'Créer un avantage en brouillon, sans aucune réclamation. Vous l’ouvrirez après vérification.');});
bind('updateState',()=>preview('setEntitlementState',[idRequired(),Number(vals('state'))],'Modifier l’état de cet avantage. Les droits déjà enregistrés ne sont pas supprimés.'));
bind('updateCap',()=>preview('setCapacity',[idRequired(),integer('capacity')],'Modifier le quota. Une valeur nulle signifie sans plafond.'));
bind('updateWindow',()=>preview('setWindow',[idRequired(),...dates()],'Modifier la période de réclamation, en UTC.'));
bind('updateCategory',()=>preview('setCategory',[idRequired(),key(vals('category'))],'Modifier la catégorie publique.'));
bind('duplicate',()=>{let n=prompt('Identifiant du nouvel avantage (ex. IA101_2026_11_17)');if(n)return preview('duplicateEntitlement',[idRequired(),key(n)],'Créer une copie en brouillon. Aucune réclamation, date ou métadonnée ne sera reprise.');});
bind('descriptor',()=>{let hash=vals('metadataHash')||(demo?'DEMO:ZERO':ethers.ZeroHash);if(!demo&&!/^0x[0-9a-fA-F]{64}$/.test(hash))throw Error('Hash de 32 octets requis.');return preview('setDescriptor',[idRequired(),vals('titleFR'),vals('titleEN'),vals('metadataURI'),hash],'Publier le titre et les métadonnées sur Ethereum. Aucun renseignement personnel.');});
bind('grant',()=>preview('adminGrantBatchToCurrentOwners',[idRequired(),members()],'Attribuer le droit aux détenteurs actuels. Toute entrée non valide annule le lot entier.'));
bind('override',()=>preview('adminGrantClaimOverride',[idRequired(),oneMember(),demo?'DEMO:RECIPIENT':recipient(),hashReason()],'EXCEPTION ADMINISTRATIVE : ce droit peut être attribué sans preuve de détention du membership. Ne pas présenter cette opération comme une auto-réclamation membre.'));
bind('revoke',()=>preview('revokeBatch',[idRequired(),members(),hashReason()],'Révoquer les droits actifs. Les billets Eventbrite déjà émis doivent être traités séparément.'));
bind('reinstate',()=>preview('reinstateClaim',[idRequired(),oneMember()],'Rétablir le droit révoqué du même bénéficiaire, sous réserve du quota.'));
bind('reassign',()=>preview('reassignRevokedClaim',[idRequired(),oneMember(),demo?'DEMO:RECIPIENT':recipient()],'Réattribuer un droit révoqué. L’ancienne demande doit être invalidée dans le registre d’émission hors chaîne.'));
bind('pause',()=>preview('pause',[],'Suspendre les auto-réclamations publiques. Les fonctions de lecture et de réparation restent actives.'));
bind('unpause',()=>preview('unpause',[],'Reprendre les auto-réclamations publiques.'));
bind('wrapperPolicy',()=>{if(demo)return preview('setSupportedNameWrapper',['DEMO:WRAPPER',true],'Simulation de support wrapper membre.');needEthers();const w=vals('wrapperAddress');if(!ethers.isAddress(w))throw Error('Adresse de wrapper non valide.');return preview('setSupportedNameWrapper',[ethers.getAddress(w),$('wrapperEnabled').checked],'Modifier la source de vérification des memberships. Ce réglage ne change jamais la source d’autorité de club.agi.eth. Revue du code et essai de régression obligatoires avant activation.');});
bind('audit',audit);bind('exportAudit',()=>download('AGI_CLUB_CLAIMS.json',auditRows));
bind('sendEmail',()=>{if(!signedPacket)throw Error('Préparez la demande signée.');const body='Bonjour Vincent,\n\nVoici ma demande de billet AGI Club signée. Merci de vérifier le reçu avant émission.\n\n'+JSON.stringify(signedPacket);location.href='mailto:president@montreal.ai?subject='+encodeURIComponent('AGI CLUB — IA 101 — demande signée à vérifier')+'&body='+encodeURIComponent(body);$('requestStatus').textContent='Votre client courriel a été sollicité. Vérifiez le message et envoyez-le vous-même. Si son contenu est tronqué, joignez le reçu JSON. Envoi non confirmé par cette page.';});
if($('modeNotice'))$('modeNotice').textContent=CFG.registryAddress?'Configuration présente. Connectez le wallet pour vérifier le réseau, le contrat et les sources d’autorité.':'NON DÉPLOYÉ / NON CONFIGURÉ. La démonstration fonctionne sans wallet. Aucun avantage réel ne peut être réclamé avant déploiement et qualification.';
if(window.ethereum?.on){for(const event of ['accountsChanged','chainChanged'])window.ethereum.on(event,()=>{requestEpoch++;for(const id of ['downloadRequest','sendEmail','relayRequest'])if($(id))$(id).disabled=true;connected=false;demo=false;contract=null;signer=null;currentMember=null;signedPacket=null;if($('claim'))$('claim').disabled=true;if($('request'))$('request').disabled=true;status('Wallet ou réseau modifié. Reconnectez-vous avant de poursuivre.',true);});}
})();
