// Public production function ABI. EVM tests compare every signature with the compiled contract.
export const EXPLORER_ABI = [
  "function CANONICAL_ENS() view returns (address)",
  "function CANONICAL_WRAPPER() view returns (address)",
  "function CLUB_AGI_ETH_NODE() view returns (bytes32)",
  "function MAX_CANONICAL_NAME_BYTES() view returns (uint256)",
  "function VERSION() view returns (string)",
  "function admin() view returns (address currentAdmin)",
  "function adminGrantBatchToCurrentOwners(bytes32 id, string[] labels)",
  "function adminGrantClaimOverride(bytes32 entitlementId, string label, address claimant, bytes32 reasonHash) returns (bytes32 node)",
  "function adminGrantClaimToCurrentOwner(bytes32 entitlementId, string label) returns (bytes32 node, address claimant)",
  "function adminInfo() view returns (address currentAdmin, address registryOwner, bool wrapped, bool expiryKnown, uint64 expiry)",
  "function adminNameWrapper() view returns (address)",
  "function claim(bytes32 entitlementId, string label) returns (bytes32 node)",
  "function claimNodeAt(bytes32 entitlementId, uint256 index) view returns (bytes32)",
  "function claimNodeCount(bytes32 entitlementId) view returns (uint256)",
  "function claimNodesPage(bytes32 id, uint256 offset, uint256 limit) view returns (bytes32[] out)",
  "function claimRecord(bytes32 entitlementId, bytes32 node) view returns (address claimant, uint64 firstClaimedAt, uint64 lastActivatedAt, uint64 revokedAt, uint32 revision, uint8 status)",
  "function claimability(bytes32 entitlementId, address claimant, string label) view returns (uint8 status, bytes32 membershipNode_, address effectiveOwner, address existingClaimant, uint8 existingClaimStatus, bool wrapped, bool expiryKnown, uint64 expiry, uint64 activeClaims, uint64 capacity, uint8 state)",
  "function claimantOf(bytes32 entitlementId, bytes32 node) view returns (address)",
  "function createEntitlement(bytes32 entitlementId, bytes32 category, uint64 capacity, uint64 opensAt, uint64 closesAt, uint8 initialState, bytes32 metadataHash)",
  "function duplicateEntitlement(bytes32 sourceId, bytes32 newId)",
  "function ensRegistry() view returns (address)",
  "function entitlement(bytes32 entitlementId) view returns (bytes32 category, bytes32 metadataHash, uint64 capacity, uint64 activeClaims, uint64 uniqueClaims, uint64 opensAt, uint64 closesAt, uint8 state, bool exists)",
  "function entitlementCount() view returns (uint256)",
  "function entitlementId(string canonicalName) pure returns (bytes32)",
  "function entitlementIdAt(uint256 index) view returns (bytes32)",
  "function entitlementIdsPage(uint256 offset, uint256 limit) view returns (bytes32[] out)",
  "function hasClaimed(bytes32 entitlementId, bytes32 node) view returns (bool)",
  "function isAdmin(address account) view returns (bool)",
  "function membershipInfo(string label) view returns (bytes32 node, address effectiveOwner, address registryOwner, bool wrapped, bool expiryKnown, uint64 expiry)",
  "function membershipNode(string label) pure returns (bytes32)",
  "function metadataURI(bytes32) view returns (string)",
  "function nameWrapperAt(uint256 index) view returns (address wrapper, bool supported)",
  "function nameWrapperCount() view returns (uint256)",
  "function pause()",
  "function paused() view returns (bool)",
  "function reassignRevokedClaim(bytes32 entitlementId, string label, address newClaimant)",
  "function reinstateClaim(bytes32 entitlementId, string label)",
  "function remainingCapacity(bytes32 entitlementId) view returns (bool capped, uint64 remaining)",
  "function revokeBatch(bytes32 id, string[] labels, bytes32 reasonHash)",
  "function revokeClaim(bytes32 entitlementId, string label, bytes32 reasonHash)",
  "function setCapacity(bytes32 entitlementId, uint64 newCapacity)",
  "function setCategory(bytes32 entitlementId, bytes32 newCategory)",
  "function setDescriptor(bytes32 id, string fr, string en, string uri, bytes32 digest)",
  "function setEntitlementState(bytes32 entitlementId, uint8 newState)",
  "function setMetadataHash(bytes32 entitlementId, bytes32 newMetadataHash)",
  "function setSupportedNameWrapper(address wrapper, bool supported)",
  "function setWindow(bytes32 entitlementId, uint64 opensAt, uint64 closesAt)",
  "function supportedNameWrapper(address wrapper) view returns (bool supported)",
  "function titleEN(bytes32) view returns (string)",
  "function titleFR(bytes32) view returns (string)",
  "function unpause()",
  "function wasEverClaimed(bytes32 entitlementId, bytes32 node) view returns (bool)"
];
